use_frameworks!

platform :ios, '9.0'

target 'SteppePayment_Example' do
  pod 'SteppePayment', :path => '../'

  target 'SteppePayment_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
